### PR TITLE
Fullscreen presentation style support for modal controllers

### PR DESCRIPTION
**Pull request by albertschulz**
By default the modal controller has used a custom presentation style, which can lead to a large view hierarchy, which is not needed in most cases, since the view controller underneath are not visible.

I would appreciate the fullscreen style per default. Its still possible to change the presentation style to custom, if care about the controller underneath

### CODE REVIEW

**Comment by leviathan** [comment]
+1 :+1:

**Comment by zoonooz** [comment]
Hello! guys,

I think the property `modalPresentationStyle` is there for default styles like `UIModalPresentationPopover` or `UIModalPresentationPageSheet`. We don't know what is it doing inside (or probably can know by using Disassemblers) and also Apple docs says `UIModalPresentationCustom ` is for custom transition delegate like this lib is using. So I prefer to use that.

I understand that can lead to large view hierarchy, My opinion is keep using `UIModalPresentationCustom` as it means and manage this by using a flag or other option.

What do you guys think.

**Comment by absolute-heike** [comment]
Hello zoonooz.

No, UIModalPresentationCustom is just for Presentations, where the fromViewController should stay visible AFTER the transition (e.g. Alerts, Overlays, etc.). UIModalPresentationFullScreen hides the fromViewController after the animation (as the default UINavigationController- and  ModalController-Transitions do).

Also since iOS 8 you also should use [transitionContext viewForKey:] instead of using [transitionContext viewControllerForKey:] and accessing the view directly. Doing this you will recognize, that viewForKey: will only return a valid view, if you use UIModalPresentationFullScreen. For UIModalPresentationCustom nil is returned, because Apple doesn't want you to mess with the background view.

**Comment by zoonooz** [comment]
Hi @absolute-heike 

Then why Apple did not make the options to be only `UIModalPresentationFullScreen` and `UIModalPresentationOverFullScreen`. it will make more sense right ? Why do we need `UIModalPresentationCustom`.

And only `UIModalPresentationCustom` in document mentions about transitionDelegate so I'm quite sure that Apple encourage us to use `UIModalPresentationCustom` if we do custom transition and want us to manage the view hierarchy by ourself.

**Comment by absolute-heike** [comment]
Hi @zoonooz,

Just have a look at the Reference:
https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIViewController_Class/#//apple_ref/c/tdef/UIModalPresentationStyle.

For __UIModalPresentationFullScreen__ it says:
_A presentation style in which the presented view covers the screen._

This also applies to custom transitions. You just tell UIKit, that __after__ the transition, the controller in the background is completely covered and can therefore be removed from the view hierarchy for performance reasons. Just try it out. If you use UIModalPresentationFullScreen everything looks exactly the same, except you don't mess up the view hierarchy.

And finally: have a look at WWDC 2013 Session 218 (around 12:00):
https://developer.apple.com/videos/wwdc/2013/#218
Here you can see the supported presentation styles:
bildschirmfoto 2015-06-25 um 20 30 06

I completely understand your confusion, as apples documentation is not very good for custom transitions.

**Comment by zoonooz** [comment]
Hi @absolute-heike ,

That's weird!! but yeah you are right. I will try to look at @albertschulz PR and see how can I support that.

Thanks

**Comment by zoonooz** [comment]
The reasons that I did't merge from @albertschulz directly are
1. I preferred to have pure Objective-C code.
2. It did't work with `UIModalPresentationCustom`. I understand that this PR is about `UIModalPresentationFullScreen` but it also have to support `UIModalPresentationCustom` too.
3. I thought it can be updated quickly so I did it myself.

Anyway I realize that I should have told you earlier. Sorry about that. I owe your guys :beers:

**Pull request closed without merging**
